### ISSUE TITLE
爬虫爬取信息不完全

### ISSUE THREAD

**Issue by Nomination-NRB** [cwjcw/xhs_spider#1]
请问运行XhsContent.py文件的时候，getdata函数中的soup=self.getHtmlSession()可以爬取部分的评论，大概6-7条左右，而且每一个笔记能爬取的评论都不定数量，这是为什么呢

**Comment by cwjcw** [comment]
我自己是可以的，你代码或者爬出来的结果贴来看看？

**Comment by Nomination-NRB** [comment]
> 我自己是可以的，你代码或者爬出来的结果贴来看看？

感谢你的回复！

我爬取的链接是：https://www.xiaohongshu.com/explore/647de826000000001203edf3
评论区图片：
![image](https://github.com/cwjcw/xhs_spider/assets/83486284/a530f8a0-05cf-4697-8860-8a7c1b44b805)

代码打印部分：
![4 0}9C ~ JLE%EVU%_7HZNP](https://github.com/cwjcw/xhs_spider/assets/83486284/f58eb002-a452-41a8-aaa1-a9be072f9616)

执行结果：
![M2A3K)}HQZEOSM`TEVF8%OG](https://github.com/cwjcw/xhs_spider/assets/83486284/c14e9970-8876-44b3-b933-3a614bb289cc)

![AG2~S)UY58RXRBPA)X0H JM](https://github.com/cwjcw/xhs_spider/assets/83486284/5eeb6ef1-d669-46a8-adfc-c4da58dd16d1)

![N 3O$ G6NH`87O1O~%Z{_SP](https://github.com/cwjcw/xhs_spider/assets/83486284/346ef4ac-b4b7-480c-9e08-f29ff066ce5a)

**Comment by cwjcw** [comment]
确实是不全，我看了下这个答主的介绍是比较全的，你可以参考https://zhuanlan.zhihu.com/p/625820877

**Comment by Nomination-NRB** [comment]
> 确实是不全，我看了下这个答主的介绍是比较全的，你可以参考https://zhuanlan.zhihu.com/p/625820877

好的，感谢回复！
